/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Documents */
        get: operations["list_documents_api_documents_get"];
        put?: never;
        /** Upload Documents */
        post: operations["upload_documents_api_documents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Document */
        get: operations["get_document_api_documents__document_id__get"];
        put?: never;
        post?: never;
        /** Delete Document */
        delete: operations["delete_document_api_documents__document_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{document_id}/chunks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Document Chunks */
        get: operations["get_document_chunks_api_documents__document_id__chunks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{document_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry Document */
        post: operations["retry_document_api_documents__document_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Stats */
        get: operations["get_stats_api_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send Chat Message */
        post: operations["send_chat_message_api_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Conversations */
        get: operations["list_conversations_api_conversations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations/{conversation_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Conversation Messages */
        get: operations["get_conversation_messages_api_conversations__conversation_id__messages_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations/{conversation_id}/messages/{message_id}/trace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Message Trace
         * @description The full trace behind one assistant turn — all retrieval candidates,
         *     every rerank result, the full contradiction filter_log. POST /chat and
         *     GET .../messages both return a trimmed summary; this is where the rest
         *     of it lives, for a "why this answer" debug view or similar.
         */
        get: operations["get_message_trace_api_conversations__conversation_id__messages__message_id__trace_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/contradictions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Contradictions
         * @description Grouped by default: N documents disagreeing pairwise on one fact
         *     produce C(N,2) distinct, individually-correct pairwise records — this
         *     groups them into one displayed conflict per underlying disagreement.
         *     Every individual pairwise record is still present, inside each group's
         *     `evidence[]`; PATCH targets an evidence item's own id, not group_id.
         */
        get: operations["list_contradictions_api_contradictions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/contradictions/{contradiction_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Contradiction */
        get: operations["get_contradiction_api_contradictions__contradiction_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Contradiction */
        patch: operations["patch_contradiction_api_contradictions__contradiction_id__patch"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnswerStage */
        AnswerStage: {
            /** Model */
            model: string;
            /** Latency Ms */
            latency_ms: number;
            /** Citations */
            citations: string[];
            /** Citations Dropped */
            citations_dropped: number;
            /** Grounded */
            grounded: boolean;
        };
        /** Body_upload_documents_api_documents_post */
        Body_upload_documents_api_documents_post: {
            /** Files */
            files: string[];
        };
        /**
         * CandidateChunk
         * @description Lightweight record for the trace — every candidate the vector search
         *     returned, before reranking or narrowing.
         */
        CandidateChunk: {
            /** Chunk Id */
            chunk_id: string;
            /** Document Id */
            document_id: string;
            /** Document Name */
            document_name: string;
            /** Vector Score */
            vector_score: number;
            /** Page Start */
            page_start: number | null;
            /** Page End */
            page_end: number | null;
            /** Section Path */
            section_path: string[];
        };
        /** ChatOptions */
        ChatOptions: {
            /** Top K */
            top_k?: number | null;
            /** Rerank */
            rerank?: boolean | null;
            /** Document Ids */
            document_ids?: string[] | null;
            /**
             * Detect Contradictions
             * @default true
             */
            detect_contradictions: boolean;
        };
        /** ChatRequest */
        ChatRequest: {
            /** Query */
            query: string;
            /** Conversation Id */
            conversation_id?: string | null;
            options?: components["schemas"]["ChatOptions"] | null;
        };
        /** ChatResponse */
        ChatResponse: {
            /** Message Id */
            message_id: string;
            /** Conversation Id */
            conversation_id: string;
            /** Answer */
            answer: string;
            /** Citations */
            citations: components["schemas"]["Citation"][];
            /**
             * Contradictions
             * @default []
             */
            contradictions: components["schemas"]["ContradictionGroupOut"][];
            /**
             * Contradictions Total
             * @default 0
             */
            contradictions_total: number;
            trace: components["schemas"]["RetrievalTraceSummary"];
            /** Grounded */
            grounded: boolean;
        };
        /** ChunkOut */
        ChunkOut: {
            /**
             * Chunk Id
             * Format: uuid
             */
            chunk_id: string;
            /** Ordinal */
            ordinal: number;
            /** Page Start */
            page_start: number | null;
            /** Page End */
            page_end: number | null;
            /** Section Path */
            section_path: string[];
            /** Char Count */
            char_count: number;
            /** Text */
            text: string;
        };
        /** ChunksResponse */
        ChunksResponse: {
            /** Chunks */
            chunks: components["schemas"]["ChunkOut"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** Citation */
        Citation: {
            /** Marker */
            marker: string;
            /** Chunk Id */
            chunk_id: string;
            /** Document Id */
            document_id: string;
            /** Document Name */
            document_name: string;
            /** Page */
            page: number | null;
            /** Section */
            section: string | null;
            /** Text */
            text: string;
        };
        /** ContextStage */
        ContextStage: {
            /** Chunks Used */
            chunks_used: string[];
            /** Neighbour Expansion */
            neighbour_expansion: boolean;
            /** Total Tokens */
            total_tokens: number;
            /** Truncated */
            truncated: boolean;
        };
        /**
         * ContradictionEvidenceItem
         * @description One pairwise record backing a group, trimmed to what's actually new
         *     versus the group's own headline fields: `type`/`severity`/`status` are
         *     the grouping key (identical across a group's evidence by construction)
         *     and `explanation`/`reconciliation` repeat near-identical LLM prose per
         *     pair — all already shown once at the group level. Fetch a specific
         *     pair's full record (including those fields) via
         *     GET /api/contradictions/{id} using this item's `id`.
         */
        ContradictionEvidenceItem: {
            /** Id */
            id: string;
            /** Confidence */
            confidence: number;
            statement_a: components["schemas"]["ContradictionStatementView"];
            statement_b: components["schemas"]["ContradictionStatementView"];
        };
        /**
         * ContradictionGroupOut
         * @description Multiple pairwise Contradiction rows can be evidence for the same
         *     underlying conflict (N documents disagreeing pairwise on one fact
         *     produces C(N,2) distinct, individually-correct pairs). This groups
         *     them for display — statement_a/statement_b are the highest-confidence
         *     pair's statements (the group's headline); `evidence` preserves every
         *     individual pairwise record so nothing is lost, just de-duplicated in
         *     the summary view. `group_id` is derived from current membership and
         *     computed fresh per request — it is not a stored, stable identifier.
         *     PATCH still operates on an individual evidence item's `id`, not on
         *     `group_id` — the underlying data model is still flat pairwise rows.
         */
        ContradictionGroupOut: {
            /** Group Id */
            group_id: string;
            /** Type */
            type: string;
            /** Severity */
            severity: string;
            /** Confidence */
            confidence: number;
            /** Status */
            status: string;
            statement_a: components["schemas"]["ContradictionStatementView"];
            statement_b: components["schemas"]["ContradictionStatementView"];
            /** Explanation */
            explanation: string;
            /** Reconciliation */
            reconciliation: string;
            /** Evidence */
            evidence: components["schemas"]["ContradictionEvidenceItem"][];
            /** Evidence Count */
            evidence_count: number;
        };
        /** ContradictionListResponse */
        ContradictionListResponse: {
            /** Contradictions */
            contradictions: components["schemas"]["ContradictionGroupOut"][];
            /** Counts */
            counts: {
                [key: string]: number;
            };
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** ContradictionPatchRequest */
        ContradictionPatchRequest: {
            /**
             * Status
             * @enum {string}
             */
            status: "open" | "resolved" | "false_positive";
            /** Note */
            note?: string | null;
        };
        /** ContradictionRecordOut */
        ContradictionRecordOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Fingerprint */
            fingerprint: string;
            /**
             * Chunk A Id
             * Format: uuid
             */
            chunk_a_id: string;
            /**
             * Chunk B Id
             * Format: uuid
             */
            chunk_b_id: string;
            /**
             * Document A Id
             * Format: uuid
             */
            document_a_id: string;
            /**
             * Document B Id
             * Format: uuid
             */
            document_b_id: string;
            /** Statement A */
            statement_a: string;
            /** Statement B */
            statement_b: string;
            /** Type */
            type: string;
            /** Severity */
            severity: string;
            /** Confidence */
            confidence: number;
            /** Explanation */
            explanation: string;
            /** Reconciliation */
            reconciliation: string;
            /** Status */
            status: string;
            /** Resolution Note */
            resolution_note: string | null;
            /** First Seen Query */
            first_seen_query: string | null;
            /** Times Seen */
            times_seen: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * Last Seen At
             * Format: date-time
             */
            last_seen_at: string;
            /** Resolved At */
            resolved_at: string | null;
        };
        /** ContradictionStage */
        ContradictionStage: {
            /** Enabled */
            enabled: boolean;
            /** Pairs Generated */
            pairs_generated: number;
            /** Pairs After Same Doc Filter */
            pairs_after_same_doc_filter: number;
            /** Cached Verdicts */
            cached_verdicts: number;
            /** Pairs Sent To Cosine */
            pairs_sent_to_cosine: number;
            /** Pairs After Cosine */
            pairs_after_cosine: number;
            /** Numeric Exemptions */
            numeric_exemptions: number;
            /** False Positive Suppressions */
            false_positive_suppressions: number;
            /** Llm Calls */
            llm_calls: number;
            /** Latency Ms */
            latency_ms: number;
            /** Verdicts Returned */
            verdicts_returned: number;
            /** Verdicts Rejected Span Check */
            verdicts_rejected_span_check: number;
            /** Verdicts Below Confidence */
            verdicts_below_confidence: number;
            /** Found */
            found: number;
            /**
             * Filter Log
             * @default []
             */
            filter_log: components["schemas"]["PairDecision"][];
            /** Error */
            error?: string | null;
        };
        /**
         * ContradictionStageSummary
         * @description Same counts as ContradictionStage, minus `filter_log` (one entry per
         *     candidate pair attempted — debug detail, not something a chat UI shows).
         *     The full log stays on the persisted Message row.
         */
        ContradictionStageSummary: {
            /** Enabled */
            enabled: boolean;
            /** Pairs Generated */
            pairs_generated: number;
            /** Pairs After Same Doc Filter */
            pairs_after_same_doc_filter: number;
            /** Cached Verdicts */
            cached_verdicts: number;
            /** Pairs Sent To Cosine */
            pairs_sent_to_cosine: number;
            /** Pairs After Cosine */
            pairs_after_cosine: number;
            /** Numeric Exemptions */
            numeric_exemptions: number;
            /** False Positive Suppressions */
            false_positive_suppressions: number;
            /** Llm Calls */
            llm_calls: number;
            /** Latency Ms */
            latency_ms: number;
            /** Verdicts Returned */
            verdicts_returned: number;
            /** Verdicts Rejected Span Check */
            verdicts_rejected_span_check: number;
            /** Verdicts Below Confidence */
            verdicts_below_confidence: number;
            /** Found */
            found: number;
            /** Error */
            error?: string | null;
        };
        /** ContradictionStatementView */
        ContradictionStatementView: {
            /** Text */
            text: string;
            /** Document Id */
            document_id: string;
            /** Document Name */
            document_name: string;
            /** Page */
            page: number | null;
            /** Section */
            section: string | null;
            /** Effective Date */
            effective_date: string | null;
        };
        /** ConversationMessagesResponse */
        ConversationMessagesResponse: {
            /**
             * Conversation Id
             * Format: uuid
             */
            conversation_id: string;
            /** Messages */
            messages: components["schemas"]["MessageOut"][];
        };
        /** ConversationOut */
        ConversationOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string | null;
            /** Message Count */
            message_count: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ConversationsResponse */
        ConversationsResponse: {
            /** Conversations */
            conversations: components["schemas"]["ConversationOut"][];
        };
        /** DocumentOut */
        DocumentOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Original Filename */
            original_filename: string;
            /** File Type */
            file_type: string;
            /** Size Bytes */
            size_bytes: number;
            /** Status */
            status: string;
            /** Page Count */
            page_count: number | null;
            /** Chunk Count */
            chunk_count: number | null;
            /** Chunks Done */
            chunks_done: number;
            /** Embedding Model */
            embedding_model: string | null;
            /** Effective Date */
            effective_date: string | null;
            /** Attempts */
            attempts: number;
            /** Error Code */
            error_code: string | null;
            /** Error Message */
            error_message: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** DocumentUploadItem */
        DocumentUploadItem: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Original Filename */
            original_filename: string;
            /** Status */
            status: string;
            /** Size Bytes */
            size_bytes: number;
            /** Duplicate */
            duplicate: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** MessageOut */
        MessageOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Role */
            role: string;
            /** Content */
            content: string;
            /** Citations */
            citations: components["schemas"]["Citation"][] | null;
            trace: components["schemas"]["RetrievalTraceSummary"] | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** PairDecision */
        PairDecision: {
            /** Chunk A Id */
            chunk_a_id: string;
            /** Chunk B Id */
            chunk_b_id: string;
            /** Cosine */
            cosine: number | null;
            /** Accepted */
            accepted: boolean;
            /** Reason */
            reason: string;
        };
        /** RerankResultEntry */
        RerankResultEntry: {
            /** Chunk Id */
            chunk_id: string;
            /** Vector Score */
            vector_score: number;
            /** Rerank Score */
            rerank_score: number;
            /** Rank Before */
            rank_before: number;
            /** Rank After */
            rank_after: number;
            /** Rank Delta */
            rank_delta: number;
            /** Used In Answer */
            used_in_answer: boolean;
        };
        /** RerankStage */
        RerankStage: {
            /** Enabled */
            enabled: boolean;
            /** Model */
            model?: string | null;
            /** Kept */
            kept: number;
            /** Latency Ms */
            latency_ms: number;
            /**
             * Results
             * @default []
             */
            results: components["schemas"]["RerankResultEntry"][];
            /**
             * Dropped
             * @default []
             */
            dropped: string[];
            /** Error */
            error?: string | null;
        };
        /** RerankStageSummary */
        RerankStageSummary: {
            /** Enabled */
            enabled: boolean;
            /** Model */
            model?: string | null;
            /** Kept */
            kept: number;
            /** Latency Ms */
            latency_ms: number;
            /** Error */
            error?: string | null;
        };
        /** RetrievalStage */
        RetrievalStage: {
            /** Top K */
            top_k: number;
            /** Returned */
            returned: number;
            /** Latency Ms */
            latency_ms: number;
            /** Candidates */
            candidates: components["schemas"]["CandidateChunk"][];
        };
        /**
         * RetrievalStageSummary
         * @description Trimmed for the response a frontend actually renders — counts and
         *     latency only. The full per-candidate list (`RetrievalStage.candidates`)
         *     is debug/audit detail, still persisted in full and available via
         *     GET /conversations/{id}/messages/{message_id}/trace.
         */
        RetrievalStageSummary: {
            /** Top K */
            top_k: number;
            /** Returned */
            returned: number;
            /** Latency Ms */
            latency_ms: number;
        };
        /** RetrievalTrace */
        RetrievalTrace: {
            /** Trace Id */
            trace_id: string;
            /** Query Raw */
            query_raw: string;
            /** Query Used For Retrieval */
            query_used_for_retrieval: string;
            /** Condensed */
            condensed: boolean;
            retrieval: components["schemas"]["RetrievalStage"];
            rerank?: components["schemas"]["RerankStage"] | null;
            context?: components["schemas"]["ContextStage"] | null;
            answer?: components["schemas"]["AnswerStage"] | null;
            contradiction_check?: components["schemas"]["ContradictionStage"] | null;
            /** Total Ms */
            total_ms?: number | null;
        };
        /**
         * RetrievalTraceSummary
         * @description What GET /chat and GET /conversations/.../messages actually return
         *     for `trace` — every field a frontend can meaningfully show (what was
         *     searched, whether reranking/contradiction-checking ran, timings), none
         *     of the per-candidate debug arrays (`retrieval.candidates`,
         *     `rerank.results`/`dropped`, `contradiction_check.filter_log`). Those
         *     stay fully persisted on the Message row; fetch them in full via
         *     GET /conversations/{id}/messages/{message_id}/trace when actually
         *     needed (e.g. a "why this answer" debug view), instead of shipping them
         *     on every chat turn.
         */
        RetrievalTraceSummary: {
            /** Trace Id */
            trace_id: string;
            /** Query Raw */
            query_raw: string;
            /** Query Used For Retrieval */
            query_used_for_retrieval: string;
            /** Condensed */
            condensed: boolean;
            retrieval: components["schemas"]["RetrievalStageSummary"];
            rerank?: components["schemas"]["RerankStageSummary"] | null;
            context?: components["schemas"]["ContextStage"] | null;
            answer?: components["schemas"]["AnswerStage"] | null;
            contradiction_check?: components["schemas"]["ContradictionStageSummary"] | null;
            /** Total Ms */
            total_ms?: number | null;
        };
        /** StatsResponse */
        StatsResponse: {
            /** Documents By Status */
            documents_by_status: {
                [key: string]: number;
            };
            /** Total Chunks */
            total_chunks: number;
            /** Qdrant Point Count */
            qdrant_point_count: number;
            /** Embedding Model */
            embedding_model: string;
        };
        /** UploadResponse */
        UploadResponse: {
            /** Documents */
            documents: components["schemas"]["DocumentUploadItem"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    list_documents_api_documents_get: {
        parameters: {
            query?: {
                status?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_documents_api_documents_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_documents_api_documents_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_document_api_documents__document_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_document_api_documents__document_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_document_chunks_api_documents__document_id__chunks_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChunksResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_document_api_documents__document_id__retry_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_stats_api_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatsResponse"];
                };
            };
        };
    };
    send_chat_message_api_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_conversations_api_conversations_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationsResponse"];
                };
            };
        };
    };
    get_conversation_messages_api_conversations__conversation_id__messages_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationMessagesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_message_trace_api_conversations__conversation_id__messages__message_id__trace_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
                message_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RetrievalTrace"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_contradictions_api_contradictions_get: {
        parameters: {
            query?: {
                status?: string | null;
                severity?: string | null;
                type?: string | null;
                document_id?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContradictionListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_contradiction_api_contradictions__contradiction_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contradiction_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContradictionRecordOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_contradiction_api_contradictions__contradiction_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contradiction_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContradictionPatchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContradictionRecordOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
